# Generated by Django 6.0 on 2026-01-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportwaste',
            name='waste_type',
            field=models.CharField(max_length=100),
        ),
    ]
